esphome:
  name: test

esp8266:
  board: esp_wroom_02

external_components:
  - source:
      type: git
      url: https://github.com/K-4U/custom_components
    components: [ yeelight_remote ]

wifi:
  ssid: !secret ssid
  password: !secret wpa2
  fast_connect: true

captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:

# Example configuration entry

wled:

# Specify the two pins of the h-bridge as PWM pins
output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_cw
    power_supply: power
    frequency: 64 Hz
    max_power: 0.85  # <- limit brightness to prevent voltage drop
  - platform: esp8266_pwm
    pin: GPIO5
    id: output_ww
    power_supply: power
    frequency: 64 Hz
    max_power: 0.85  # <- limit brightness to prevent voltage drop
    
power_supply:
  - id: power
    pin: GPIO4
    enable_time: 0s
    keep_on_time: 0s

light:
  - platform: cwww
    id: light1
    default_transition_length: 0s
    constant_brightness: true
    gamma_correct: 0
    name: "Yeelight Screenbar face"
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
  - platform: neopixelbus
    num_leds: 40
    pin: GPIO13
    name: "Yeelight Screenbar back LED Ring"
    variant: WS2812
    id: LED_ring
    power_supply: power
    effects:
      - wled:
          port: 21324
      - addressable_rainbow:
      - random:
      - strobe:
      - flicker:
      - addressable_color_wipe:
    # Limit the brightness to prevent power supply from browning out.
    color_correct: [90%, 90%, 90%]

uart:
  - id: remote_bus
    baud_rate: 4800
    rx_pin: GPIO2

yeelight_remote:
  on_press:
    - light.toggle: light1
  on_left:
    then:
      - light.dim_relative:
          id: light1
          relative_brightness: -5%
  on_right:
    then:
      - light.dim_relative:
          id: light1
          relative_brightness: 5%
  on_long_press:
    - light.toggle: LED_ring
